'''
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

  1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

  It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

  Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
'''

from math import fabs

def pentagonal_numbers(limit=10**4):
      pentagonal_collection = set([ int(_ * (3 * _ - 1) / 2) for _ in range(1, limit)])

      for n in pentagonal_collection:
          for p in pentagonal_collection:
            difference = int(abs(n - p))
            addition = n + p

            if difference in pentagonal_collection and addition in pentagonal_collection:
                return n, p, difference


if __name__ == "__main__":
    answer = pentagonal_numbers()

    print(answer)
