'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

  Triangle     Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
  Pentagonal     Pn=n(3n−1)/2     1, 5, 12, 22, 35, ...
  Hexagonal     Hn=n(2n−1)     1, 6, 15, 28, 45, ...
  It can be verified that T285 = P165 = H143 = 40755.

  Find the next triangle number that is also pentagonal and hexagonal.
'''

if __name__ == "__main__":
  t_n = 3
  p_n = 5
  h_n = 6
  t_count = 2
  p_count = 2
  h_count = 2
  values = set([t_n, p_n, h_n])

  memo = list()

  while len(memo) < 2:
    t = (t_n, t_count, 't')
    p = (p_n, p_count, 'p')
    h = (h_n, h_count, 'h')

    smallest = min([t,p,h])

    if smallest[2] == 't':
        t_count += 1
        t_n = int(t_count*(t_count+1)/2)
    elif smallest[2] == 'p':
        p_count += 1
        p_n = int(p_count*(3*p_count-1)/2)
    else:
        h_count += 1
        h_n = int(h_count*(2*h_count -1))

    values = set([t_n, p_n, h_n])

    if len(values) == 1:
        print((t_count, p_count, h_count))
        print(values)
        memo.append((t_count, p_count, h_count))

  print(memo)



